services:
  - type: web
    name: voltix-ml-api
    env: python
    buildCommand: ([ -d SmartCharge-ML ] && cd SmartCharge-ML || true) && pip install -r requirements.txt && python train_and_test_demand_model.py && python check_data.py
    startCommand: ([ -d SmartCharge-ML ] && cd SmartCharge-ML || true) && uvicorn api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8

